applications:
  argo-apps-ops:
    destination:
      name: in-cluster
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: argo-cd
    sources:
    - ref: values
      repoURL: https://github.com/chaya-odds/poc-argo.git
      targetRevision: main
    - chart: argocd-apps
      helm:
        releaseName: argo-apps
        valueFiles:
        - $values/ops/argo-apps/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.0.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true

projects:
  argo-cd:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: in-cluster
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: non-prod
      namespace: "*"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: in-cluster
      namespace: "*"
    - name: non-prod
      namespace: "*"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
