applications:
  argo-apps:
    destination:
      name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    info: null
    project: ops
    source:
      directory:
        recurse: true
      path: apps
      repoURL: https://github.com/oddsteam/odds-cloud-apps.git
      targetRevision: main
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  argo-apps-ops:
    destination:
      name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: argo-cd
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: argocd-apps
      helm:
        releaseName: argo-apps
        valueFiles:
        - $values/ops/argo-apps/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.0.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  argo-cd-image-updater:
    destination:
      name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: argo-cd
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: argocd-image-updater
      helm:
        releaseName: argo-cd-image-updater
        valueFiles:
        - $values/ops/argo-cd-image-updater/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.10.1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  ceph-csi-cephfs-non-prod:
    destination:
      name: non-prod
      namespace: ceph-csi-cephfs
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ceph-csi-cephfs-non-prod
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: ceph-csi-cephfs
      helm:
        releaseName: ceph-csi-cephfs
        valueFiles:
        - $values/ops/ceph-csi-cephfs/values-non-prod.yaml
      repoURL: https://ceph.github.io/csi-charts
      targetRevision: 3.11.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  ceph-csi-cephfs-ops:
    destination:
      name: ops
      namespace: ceph-csi-cephfs
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ceph-csi-cephfs-ops
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: ceph-csi-cephfs
      helm:
        releaseName: ceph-csi-cephfs
        valueFiles:
        - $values/ops/ceph-csi-cephfs/values-ops.yaml
      repoURL: https://ceph.github.io/csi-charts
      targetRevision: 3.11.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  external-secret-non-prod:
    destination:
      name: non-prod
      namespace: external-secret
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: non-prod
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: external-secrets
      helm:
        releaseName: external-secrets
        valueFiles:
        - $values/ops/external-secrets/values-nonprod.yaml
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.2
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  ingress-nginx-ops:
    destination:
      name: ops
      namespace: ingress-nginx
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ingress-nginx-ops
    sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            admissionWebhooks:
              enabled: true
              annotations:
                argocd.argoproj.io/hook: PostSync
              patch:
                enabled: true
            service:
              type: NodePort
              nodePorts:
                https: 30285
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  monitoring:
    destination:
      name: ops
      namespace: monitoring
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: monitoring
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: kube-prometheus-stack
      helm:
        releaseName: monitoring
        valueFiles:
        - $values/ops/monitoring/values.yaml
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 65.5.1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  rabbitmq-non-prod:
    destination:
      name: non-prod
      namespace: rabbitmq-bitnami
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: non-prod
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: rabbitmq
      helm:
        releaseName: rabbitmq
        valueFiles:
        - $values/ops/rabbitmq/values.yaml
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.0.5
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  vault:
    additionalannotations:
      argocd.argoproj.io/compare-options: ServerSideDiff=true
    destination:
      name: ops
      namespace: vault
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ops
    sources:
    - ref: values
      repoURL: https://github.com/oddsteam/odds-cloud-deployment.git
      targetRevision: main
    - chart: vault
      helm:
        releaseName: vault
        valueFiles:
        - $values/ops/vault/values.yaml
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
projects:
  argo-cd:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ceph-csi-cephfs-non-prod:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: non-prod
      namespace: ceph-csi-cephfs
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ceph-csi-cephfs-ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: ceph-csi-cephfs
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  guestbook:
    description: Example Project
    destinations:
    - name: ops
      namespace: guestbook
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ingress-nginx-ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: ingress-nginx
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  monitoring:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: kube-system
    - name: ops
      namespace: monitoring
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  non-prod:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: non-prod
      namespace: "*"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: "*"
    - name: non-prod
      namespace: "*"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"