applications:
  argo-apps-ops:
    destination:
      name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: argo-cd
    sources:
    - ref: values
      repoURL: https://github.com/chaya-odds/poc-argo.git
      targetRevision: main
    - chart: argocd-apps
      helm:
        releaseName: argo-apps
        valueFiles:
        - $value/argo-apps/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.0.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  ingress-nginx-ops:
    destination:
      name: ops
      namespace: ingress-nginx
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: ingress-nginx-ops
    sources:
    - chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            admissionWebhooks:
              enabled: true
              annotations:
                argocd.argoproj.io/hook: PostSync
              patch:
                enabled: true
            service:
              type: NodePort
              nodePorts:
                https: 30285
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.10.1
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
projects:
  argo-cd:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: argo-cd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ingress-nginx-ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: ingress-nginx
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"
  ops:
    clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    destinations:
    - name: ops
      namespace: "*"
    - name: non-prod
      namespace: "*"
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
    roles: []
    sourceRepos:
    - "*"